### ISSUE TITLE
parse4 is not a function

### ISSUE THREAD

**Issue by panw3i** [lisonge/visit-counter#1]
```

{
message: "parse4 is not a function",
stack: "TypeError: parse4 is not a function at renderToString (worker.js:23136:21) at handleRequest (worker.js:23189:19)"
}

```

**Comment by lisonge** [comment]
@panw3i 

thank your issue

see [taoqf/node-html-parser/pull/166#issuecomment-951675397](https://github.com/taoqf/node-html-parser/pull/166#issuecomment-951675397) and [evanw/esbuild/issues/1719](https://github.com/evanw/esbuild/issues/1719)

i will fix this bug later by rewrite esbuild config

if you just want compile code, you can just delete `visit-counter/node_modules/node-html-parser/package.json`  line 104-174
```json
,
	"exports": {
		"require": "./dist/index.js",
		"import": "./esm/index.js"
	}
```

**Comment by lisonge** [comment]
fix by <https://github.com/lisonge/visit-counter/commit/f447efa28a2c3a0a68c8daa2d95a804d92b7efba>
